#!/usr/bin/env bash
# installs nginx on webserver
# changes default webpage to print "Holberton School"
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
