#!/usr/bin/env bash
#prints "Holberton School" 10 times using while loop
let -i i=0
while [ $i -le 9 ] 
do 
if [ $i == 3 ]
then  
echo "bad luck"
elif [ $i == 7 ]
then
echo "good luck"
else 
echo "Holberton School"
fi
let i++
done
